all:
	@cd src && make all

clean:
	rm -f penn src/*.o src/*.d

help:
	@echo "Usage:"
	@echo "make [all]\t\tBuild the executable file"
	@echo "make clean\t\tRemove all files generated by make"
	@echo "make help\t\tDisplay this help"

.PHONY: all clean help